package com.househost.booking.checkout.application.service;

import com.househost.booking.booking.application.service.BookingService;
import com.househost.booking.booking.domain.model.Booking;
import com.househost.booking.booking.domain.model.BookingStatus;
import com.househost.booking.checkout.application.dto.CheckOutRequestDTO;
import com.househost.booking.checkout.application.dto.CheckOutRatingRequestDTO;
import com.househost.booking.checkout.application.dto.CheckOutResponseDTO;
import com.househost.booking.checkout.application.port.out.CheckOutAuditPort;
import com.househost.booking.checkout.application.port.out.CheckOutPersistencePort;
import com.househost.booking.checkout.domain.model.CheckOut;
import com.househost.booking.checkout.domain.model.CheckOutStatus;
import com.househost.guest.domain.model.Guest;
import com.househost.room.domain.model.Room;
import com.househost.room.domain.model.RoomStatus;
import com.househost.room.domain.model.RoomType;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.annotation.EnableTransactionManagement;

import javax.sql.DataSource;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicBoolean;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

@SpringJUnitConfig(CheckOutTransactionIntegrationTest.TestConfiguration.class)
class CheckOutTransactionIntegrationTest {

    @Autowired
    private CheckOutService checkOutService;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    @Qualifier("failGuestHistoryApplication")
    private AtomicBoolean failGuestHistoryApplication;

    @Autowired
    @Qualifier("failRatingCreation")
    private AtomicBoolean failRatingCreation;

    @BeforeEach
    void setUpDatabase() {
        jdbcTemplate.execute("drop table if exists check_out_audits");
        jdbcTemplate.execute("drop table if exists ratings");
        jdbcTemplate.execute("drop table if exists check_outs");
        jdbcTemplate.execute("drop table if exists guest_history");
        jdbcTemplate.execute("""
                create table guest_history (
                    guest_id bigint primary key,
                    stay_count int not null,
                    total_spent decimal(19,2) not null
                )
                """);
        jdbcTemplate.execute("""
                create table check_outs (
                    id bigint primary key,
                    booking_id bigint not null unique,
                    status varchar(30) not null,
                    guest_history_applied boolean not null
                )
                """);
        jdbcTemplate.execute("""
                create table ratings (
                    id bigint generated by default as identity primary key,
                    booking_id bigint not null unique,
                    comfort_score int not null
                )
                """);
        jdbcTemplate.execute("""
                create table check_out_audits (
                    id bigint generated by default as identity primary key,
                    event_type varchar(80) not null,
                    check_out_id bigint
                )
                """);
        jdbcTemplate.update(
                "insert into guest_history (guest_id, stay_count, total_spent) values (?, ?, ?)",
                7L,
                0,
                BigDecimal.ZERO
        );
        failGuestHistoryApplication.set(false);
        failRatingCreation.set(false);
    }

    @Test
    void completedCheckoutIsAppliedOnceAcrossDatabaseReloadAndRetry() {
        CheckOutResponseDTO checkOutResponseDTO = checkOutService.create(completedRequest());

        checkOutService.update(checkOutResponseDTO.getId(), completedRequest());

        assertEquals(1, integerValue("select stay_count from guest_history where guest_id = 7"));
        assertEquals(
                new BigDecimal("700.00"),
                decimalValue("select total_spent from guest_history where guest_id = 7")
        );
        assertEquals(
                1,
                integerValue("select count(*) from check_outs where guest_history_applied = true")
        );
        assertEquals(1, integerValue("select count(*) from ratings where booking_id = 23"));
        assertEquals(2, integerValue("select count(*) from check_out_audits"));
    }

    @Test
    void guestHistoryFailureRollsBackCheckoutEvidenceAndSuccessAudit() {
        failGuestHistoryApplication.set(true);

        assertThrows(
                IllegalStateException.class,
                () -> checkOutService.create(completedRequest())
        );

        assertEquals(0, integerValue("select stay_count from guest_history where guest_id = 7"));
        assertEquals(0, integerValue("select count(*) from check_outs"));
        assertEquals(0, integerValue("select count(*) from check_out_audits"));
    }

    @Test
    void ratingFailureRollsBackCheckoutGuestHistoryAndRating() {
        failRatingCreation.set(true);

        assertThrows(
                IllegalStateException.class,
                () -> checkOutService.create(completedRequest())
        );

        assertEquals(0, integerValue("select stay_count from guest_history where guest_id = 7"));
        assertEquals(0, integerValue("select count(*) from ratings"));
        assertEquals(0, integerValue("select count(*) from check_outs"));
        assertEquals(0, integerValue("select count(*) from check_out_audits"));

        failRatingCreation.set(false);
        checkOutService.create(completedRequest());

        assertEquals(1, integerValue("select count(*) from ratings where booking_id = 23"));
        assertEquals(1, integerValue("select count(*) from check_outs"));
    }

    private CheckOutRequestDTO completedRequest() {
        CheckOutRequestDTO checkOutRequestDTO = new CheckOutRequestDTO();
        checkOutRequestDTO.bookingId = 23L;
        checkOutRequestDTO.actualCheckOutAt = LocalDateTime.of(2026, 8, 12, 11, 30);
        checkOutRequestDTO.roomInspected = true;
        checkOutRequestDTO.rating = completeRating();
        checkOutRequestDTO.status = CheckOutStatus.COMPLETED;
        return checkOutRequestDTO;
    }

    private CheckOutRatingRequestDTO completeRating() {
        CheckOutRatingRequestDTO checkOutRatingRequestDTO = new CheckOutRatingRequestDTO();
        checkOutRatingRequestDTO.checkInProcedureScore = 5;
        checkOutRatingRequestDTO.checkOutProcedureScore = 4;
        checkOutRatingRequestDTO.accommodationCleanlinessScore = 5;
        checkOutRatingRequestDTO.teamCommunicationScore = 4;
        checkOutRatingRequestDTO.locationScore = 5;
        checkOutRatingRequestDTO.comfortScore = 4;
        return checkOutRatingRequestDTO;
    }

    private Integer integerValue(String sql) {
        return jdbcTemplate.queryForObject(sql, Integer.class);
    }

    private BigDecimal decimalValue(String sql) {
        return jdbcTemplate.queryForObject(sql, BigDecimal.class);
    }

    @Configuration
    @EnableTransactionManagement(proxyTargetClass = true)
    static class TestConfiguration {

        @Bean
        DataSource dataSource() {
            JdbcDataSource jdbcDataSource = new JdbcDataSource();
            jdbcDataSource.setURL("jdbc:h2:mem:checkout_history;DB_CLOSE_DELAY=-1");
            jdbcDataSource.setUser("sa");
            return jdbcDataSource;
        }

        @Bean
        JdbcTemplate jdbcTemplate(DataSource dataSource) {
            return new JdbcTemplate(dataSource);
        }

        @Bean
        PlatformTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }

        @Bean
        AtomicBoolean failGuestHistoryApplication() {
            return new AtomicBoolean(false);
        }

        @Bean
        AtomicBoolean failRatingCreation() {
            return new AtomicBoolean(false);
        }

        @Bean
        Booking booking() {
            Guest guest = new Guest("Maria Silva", null, "11999999999", null);
            guest.restorePersistenceState(7L, null, List.of(), null, null);
            Room room = new Room(
                    "101",
                    RoomType.DOUBLE,
                    2,
                    new BigDecimal("350.00"),
                    RoomStatus.OCCUPIED
            );
            room.restorePersistenceState(1L, null, null);
            Booking booking = new Booking(
                    guest,
                    room,
                    LocalDate.of(2026, 8, 10),
                    LocalDate.of(2026, 8, 12),
                    BookingStatus.IN_STAY,
                    new BigDecimal("700.00")
            );
            booking.restorePersistenceState(
                    23L,
                    booking.getPaymentStatus(),
                    null,
                    null,
                    null,
                    null,
                    false,
                    null,
                    null,
                    null
            );
            return booking;
        }

        @Bean
        BookingService bookingService(Booking booking) {
            BookingService bookingService = mock(BookingService.class);
            when(bookingService.findBooking(23L)).thenReturn(booking);
            return bookingService;
        }

        @Bean
        CheckOutValidationService checkOutValidationService() {
            return mock(CheckOutValidationService.class);
        }

        @Bean
        CheckOutParticipantNotifier checkOutParticipantNotifier(
                JdbcTemplate jdbcTemplate,
                @Qualifier("failGuestHistoryApplication")
                AtomicBoolean failGuestHistoryApplication,
                @Qualifier("failRatingCreation")
                AtomicBoolean failRatingCreation
        ) {
            CheckOutParticipantNotifier checkOutParticipantNotifier =
                    mock(CheckOutParticipantNotifier.class);
            doAnswer(invocation -> {
                CheckOut checkOut = invocation.getArgument(0);
                if (checkOut.shouldApplyGuestHistory()) {
                    jdbcTemplate.update("""
                            update guest_history
                            set stay_count = stay_count + 1,
                                total_spent = total_spent + ?
                            where guest_id = ?
                            """, checkOut.getBooking().getTotalAmount(), checkOut.getGuest().getId());
                    if (failGuestHistoryApplication.get()) {
                        throw new IllegalStateException("guest persistence failure");
                    }
                    CheckOutRatingRequestDTO checkOutRatingRequestDTO =
                            invocation.getArgument(1);
                    jdbcTemplate.update(
                            "insert into ratings (booking_id, comfort_score) values (?, ?)",
                            checkOut.getBooking().getId(),
                            checkOutRatingRequestDTO.comfortScore
                    );
                    if (failRatingCreation.get()) {
                        throw new IllegalStateException("rating persistence failure");
                    }
                }
                return Optional.empty();
            }).when(checkOutParticipantNotifier).notifyCompletion(
                    any(CheckOut.class),
                    any(CheckOutRatingRequestDTO.class),
                    org.mockito.ArgumentMatchers.isNull()
            );
            return checkOutParticipantNotifier;
        }

        @Bean
        CheckOutAuditPort checkOutAuditPort(JdbcTemplate jdbcTemplate) {
            return new CheckOutAuditPort() {
                @Override
                public void record(
                        String eventType,
                        Long entityId,
                        Map<String, Object> metadataMap
                ) {
                    jdbcTemplate.update(
                            "insert into check_out_audits (event_type, check_out_id) values (?, ?)",
                            eventType,
                            entityId
                    );
                }
            };
        }

        @Bean
        CheckOutPersistencePort checkOutPersistencePort(
                JdbcTemplate jdbcTemplate,
                Booking booking
        ) {
            return new JdbcCheckOutPersistencePort(jdbcTemplate, booking);
        }

        @Bean
        CheckOutService checkOutService(
                CheckOutPersistencePort checkOutPersistencePort,
                BookingService bookingService,
                CheckOutParticipantNotifier checkOutParticipantNotifier,
                CheckOutAuditPort checkOutAuditPort,
                CheckOutValidationService checkOutValidationService
        ) {
            return new CheckOutService(
                    checkOutPersistencePort,
                    bookingService,
                    checkOutParticipantNotifier,
                    checkOutAuditPort,
                    checkOutValidationService
            );
        }
    }

    private static final class JdbcCheckOutPersistencePort implements CheckOutPersistencePort {

        private final JdbcTemplate jdbcTemplate;
        private final Booking booking;

        private JdbcCheckOutPersistencePort(JdbcTemplate jdbcTemplate, Booking booking) {
            this.jdbcTemplate = jdbcTemplate;
            this.booking = booking;
        }

        @Override
        public CheckOut save(CheckOut checkOut) {
            if (checkOut.getId() == null) {
                Long id = jdbcTemplate.queryForObject(
                        "select coalesce(max(id), 0) + 1 from check_outs",
                        Long.class
                );
                jdbcTemplate.update("""
                        insert into check_outs (
                            id, booking_id, status, guest_history_applied
                        ) values (?, ?, ?, ?)
                        """,
                        id,
                        booking.getId(),
                        checkOut.getStatus().name(),
                        checkOut.isGuestHistoryApplied()
                );
                checkOut.restorePersistenceState(id, false, null, null);
                return checkOut;
            }
            jdbcTemplate.update("""
                    update check_outs
                    set status = ?,
                        guest_history_applied = ?
                    where id = ?
                    """,
                    checkOut.getStatus().name(),
                    checkOut.isGuestHistoryApplied(),
                    checkOut.getId()
            );
            return checkOut;
        }

        @Override
        public List<CheckOut> findAll() {
            return List.of();
        }

        @Override
        public Optional<CheckOut> findById(Long id) {
            return find(id, false);
        }

        @Override
        public Optional<CheckOut> findByIdForUpdate(Long id) {
            return find(id, true);
        }

        @Override
        public Optional<CheckOut> findByBookingId(Long bookingId) {
            return Optional.empty();
        }

        @Override
        public void delete(CheckOut checkOut) {
            jdbcTemplate.update("delete from check_outs where id = ?", checkOut.getId());
        }

        private Optional<CheckOut> find(Long id, boolean lockForUpdate) {
            String sql = """
                    select status, guest_history_applied
                    from check_outs
                    where id = ?
                    """ + (lockForUpdate ? " for update" : "");
            List<CheckOut> checkOutList = jdbcTemplate.query(sql, (resultSet, rowNumber) -> {
                CheckOut checkOut = new CheckOut(
                        booking,
                        booking.getGuest(),
                        booking.getRoom(),
                        LocalDateTime.of(2026, 8, 12, 11, 30),
                        true,
                        true,
                        true,
                        true,
                        BigDecimal.ZERO,
                        BigDecimal.ZERO,
                        "reception",
                        null,
                        CheckOutStatus.valueOf(resultSet.getString("status"))
                );
                checkOut.restorePersistenceState(
                        id,
                        resultSet.getBoolean("guest_history_applied"),
                        null,
                        null
                );
                return checkOut;
            }, id);
            return checkOutList.stream().findFirst();
        }
    }
}
